[package]
name = "migration"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm-migration = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
tokio = { version = "1.49", features = ["full"] }
async-trait = "0.1"

[dependencies.entity]
path = "../entity"
